language: generic
services: docker
os: linux

stages:
  - docker

script:
  - cd $TRAVIS_BUILD_DIR/docker
  - make ${TARGET_IMAGE}

after_success:
  - if ! [[ "$TRAVIS_REPO_SLUG" = "diegoferigo/devenv" && "$TRAVIS_BRANCH" = "master" && "$TRAVIS_PULL_REQUEST" = "false" ]] ; then travis_terminate 0 ; fi
  - docker login --username=$DOCKERHUB_USERNAME --password=$DOCKERHUB_PASSWORD
  - make push_${TARGET_IMAGE}
  - if [ "$IS_LATEST" = "true" ] ; then make push_latest ; fi

jobs:
  include:
    # Disable test stage
    - stage: test
      if: env(DUMMYVAR) is present
    # docker stage
    - &devenv_template
      stage: docker
      env:
        - TARGET_IMAGE="intel"
        - IS_LATEST=true
        - PUSH_TO_DOCKERHUB=true
    - <<: *devenv_template
      env:
        - TARGET_IMAGE="nvidia"
        - IS_LATEST=false
        - PUSH_TO_DOCKERHUB=true
